services:
  db:
    image: postgres:16
    container_name: postgres_server
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env.prod
    restart: on-failure
  redis:
    image: redis:7
    container_name: redis_server
    command: --port 5370
    expose:
      - 5370
    env_file:
      - .env.prod
    restart: on-failure
  app:
    build: .
    container_name: fastapi_server
    command: ["/app/scripts/start.sh"]
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis